// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProject(arg1, arg2) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2);
}

export function CreateRule(arg1, arg2) {
  return window['go']['main']['App']['CreateRule'](arg1, arg2);
}

export function DeleteProject(arg1, arg2) {
  return window['go']['main']['App']['DeleteProject'](arg1, arg2);
}

export function DeleteRule(arg1, arg2) {
  return window['go']['main']['App']['DeleteRule'](arg1, arg2);
}

export function ImportFolder(arg1, arg2) {
  return window['go']['main']['App']['ImportFolder'](arg1, arg2);
}

export function ListProjects(arg1) {
  return window['go']['main']['App']['ListProjects'](arg1);
}

export function ListRules(arg1, arg2) {
  return window['go']['main']['App']['ListRules'](arg1, arg2);
}

export function UpdateProject(arg1, arg2) {
  return window['go']['main']['App']['UpdateProject'](arg1, arg2);
}

export function UpdateRule(arg1, arg2) {
  return window['go']['main']['App']['UpdateRule'](arg1, arg2);
}
