// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {db} from '../models';

export function CreateProject(arg1:context.Context,arg2:db.Project):Promise<void>;

export function CreateRule(arg1:context.Context,arg2:db.Rule):Promise<void>;

export function DeleteProject(arg1:context.Context,arg2:string):Promise<void>;

export function DeleteRule(arg1:context.Context,arg2:string):Promise<void>;

export function ImportFolder(arg1:context.Context,arg2:string):Promise<void>;

export function ListProjects(arg1:context.Context):Promise<Array<db.Project>>;

export function ListRules(arg1:context.Context,arg2:string):Promise<Array<db.Rule>>;

export function UpdateProject(arg1:context.Context,arg2:db.Project):Promise<void>;

export function UpdateRule(arg1:context.Context,arg2:db.Rule):Promise<void>;
